# navbar
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# sidebar
## display: post / always / hide / remove
sidebar:
  display: post

# comments
comments:
  post: true
  about: true

## Friends Link
friends:
  "Dudley Storey": "http://thenewcode.com"
  Ahonn: http://www.ahonn.me
  "Sean Sun": http://pinggod.com
  acwong: http://blog.acwong.org

# Analytics
## Baidu Analytics
baidu_analytics: 
## Google Analytics
google_analytics: UA-78709503-1

# Comments
## Duoshuo
# duoshuo_shortname: ahonn
## Disqus
disqus_shortname: uedsky

# Social links
social:
  email: mailto:uedsky@gmail.com
  github: https://github.com/yangg
  codepen: http://codepen.io/yangg
  rss: /atom.xml
